export const ProjectsData = {
  Python: {
    Mini: [
      "Rock, Paper, Scissors Game",
      "Guess the Number Game",
      "To-Do List Application",
      "Weather Forecast App",
      "URL Shortener Tool",
      "Password Generator Program",
      "Image Gallery Creator",
      "Contact Book Application",
      "Currency Converter Tool",
      "Dice Rolling Simulator",
    ],
    Intermediate: [
      "Bubble sort visualizer using PyGame",
      "Caller ID Lookup using Python",
      "Flappy Bird Game in Pygame",
      "Personalized Task Manager in Python",
      "Download Instagram profile pic using Python",
      "Voice Assistant using python",
      "Voice search Wikipedia using Python",
      "Convert Text to Speech in Python",
      "GUI Marksheet using Python",
      "Simple Calculator using Python",
      "Student Management System using Python",
    ],
    Advance: [
      "Blockchain Implementation",
      "Real-Time Language Translator",
      "Automated Trading System",
      "Network Port Scanner",
      "Data Compression Tool",
      "Voice Assistant with Speech Recognition",
      "Web Crawler and Search Engine",
      "Multiplayer Online Game",
      "Virtual File System",
      "Automated Code Review Tool",
    ],
  },

  "ML/AI": {
    Mini: [
      "Sentiment Analysis on Social Media Data",
      "Handwritten Digit Recognition",
      "Image Classification (e.g., Cats vs. Dogs)",
      "Spam Email Classifier",
      "Movie Recommendation System",
      "Predicting House Prices",
      "Customer Churn Prediction",
      "Fake News Detection",
      "Facial Emotion Recognition",
      "Credit Card Fraud Detection",
    ],
    Intermediate: [
      "Stock Price Prediction",
      "Customer Segmentation",
      "Image Style Transfer",
      "Anomaly Detection in Time Series Data",
      "Text Summarization",
      "Credit Risk Assessment",
      "Natural Language Generation",
      "Music Genre Classification",
      "Image Object Detection",
      "Movie Genre Classification",
    ],
    Advance: [
      "Natural Language Processing for Sentiment Analysis",
      "Reinforcement Learning for Game Playing",
      "Fraud Detection in Financial Transactions",
      "Chatbot with Sequence-to-Sequence Models",
      "Predictive Maintenance for Industrial Equipment",
      "Stock Market Trend Prediction using Time Series Analysis",
      "Speech Recognition with Deep Learning Models",
      "Personalized Marketing Recommendation System",
      "Medical Diagnosis using Machine Learning",
      "News Topic Modeling and Classification",
    ],
  },

  "Mobile App Development": {
    Mini: [
      "To-Do List App",
      "Weather Forecast App",
      "Calorie Tracker",
      "Flashlight App",
      "Note-taking App",
      "Currency Converter",
      "Alarm Clock App",
      "Unit Converter",
      "Tip Calculator",
      "BMI Calculator",
    ],
    Intermediate: [
      "Recipe Sharing App",
      "Language Learning App",
      "Expense Tracker",
      "Fitness Tracker",
      "E-commerce Shopping App",
      "Social Media Feed App",
      "Event Scheduler",
      "Travel Planning App",
      "Music Streaming App",
      "Public Transportation Navigator",
    ],
    Advance: [
      "Real-time Chat App",
      "Augmented Reality (AR) Game",
      "Food Delivery App with GPS Tracking",
      "Video Streaming and Recording App",
      "Online Marketplace App",
      "Voice Assistant App",
      "Machine Learning-based Recommendation App",
      "AR Navigation App for Indoor Spaces",
      "Health Monitoring and Analysis App",
      "Cryptocurrency Wallet and Exchange App",
    ],
  },

  "Web Development": {
    Mini: [
      "Personal Portfolio Website",
      "To-Do List Web App",
      "Weather Forecast Web App",
      "Recipe Collection Web App",
      "Random Quote Generator",
      "Blog or Journal Web App",
      "Contact Form Web App",
      "Currency Converter Web App",
      "Note-taking Web App",
      "Event Countdown Web App",
    ],
    Intermediate: [
      "E-commerce Website with Shopping Cart",
      "Social Media Dashboard",
      "Task Management System",
      "Recipe Sharing Platform",
      "Real Estate Listings Website",
      "Online Survey and Polling Web App",
      "Health and Fitness Tracker",
      "Stock Market Watchlist",
      "Job Board and Application Platform",
      "File Sharing and Collaboration Web App",
    ],
    Advance: [
      "Real-time Chat Application",
      "Video Streaming Platform",
      "Online Learning Management System",
      "Social Networking Website",
      "Project Management and Collaboration Platform",
      "Financial Dashboard and Analysis Tool",
      "Music Streaming Service",
      "AI-powered Personalized News Aggregator",
      "Online Booking and Reservation System",
      "Crowdfunding and Fundraising Platform",
    ],
  },

  "Computer Vision": {
    Mini: [
      "Image Filter Application",
      "Face Detection in Images",
      "Color Detection in Images",
      "QR Code Reader",
      "Object Counting in Images",
      "Image Cropping Tool",
      "Edge Detection in Images",
      "Image Compression Tool",
      "Image Resizing Tool",
      "Image Flip and Rotation Tool",
    ],
    Intermediate: [
      "Handwritten Digit Recognition",
      "License Plate Recognition System",
      "Emotion Recognition from Images",
      "Document Scanner Application",
      "Image Stitching for Panorama",
      "Automatic Image Captioning",
      "Optical Character Recognition (OCR)",
      "Motion Detection in Video Streams",
      "Facial Landmark Detection",
      "Background Removal from Images",
    ],
    Advance: [
      "Real-time Object Detection in Videos",
      "Style Transfer for Images",
      "Semantic Segmentation of Images",
      "Video Super-Resolution",
      "Human Pose Estimation",
      "Person Re-Identification in Video Surveillance",
      "DeepFake Detection",
      "Medical Image Analysis for Diagnostics",
      "Gesture Recognition from Images",
      "Image-Based 3D Reconstruction",
    ],
  },

  "Web Scraping/Automation": {
    Mini: [
      "Scrape Weather Data from a Website",
      "Extract News Headlines from a News Website",
      "Automate Social Media Post Scheduling",
      "Track Product Prices on an E-commerce Site",
      "Scrape Quotes from a Quote Website",
      "Automate Email Responses",
      "Extract Job Postings from Job Boards",
      "Monitor Stock Prices",
      "Gather Real Estate Listings Data",
      "Automate Web Form Submission",
    ],
    Intermediate: [
      "Build a Web Crawler for Crawling Multiple Websites",
      "Scrape Data from Dynamic Websites using Selenium",
      "Automate Data Entry from Excel to Web Application",
      "Extract Reviews and Ratings from Product Pages",
      "Create a Price Comparison Web App",
      "Automate File Download and Organization",
      "Scrape Financial Data for Analysis",
      "Web Scraping and Analysis of Social Media Data",
      "Build an Automated Web Testing Framework",
      "Scrape Images and Metadata from Image Galleries",
    ],
    Advance: [
      "Build a News Aggregator with Sentiment Analysis",
      "Web Scraping and Translation of Multilingual Content",
      "Automate Data Visualization and Reporting",
      "Scrape and Analyze User-generated Content",
      "Create a Recipe Recommender System",
      "Scrape and Summarize Research Papers",
      "Automate Webinar Registration and Attendance",
      "Scrape Data for Market Research and Competitive Analysis",
      "Build a Content Aggregator for Blogs and Articles",
      "Web Scraping and Natural Language Processing for Chatbots",
    ],
  },
};
